version: '3.8'

services:
  app:
    build: .
    restart: always
    expose:
      - 5055

  nginx:
    image: nginx:latest
    ports:
      - "5055:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
