version: '3'

services:
  app:
    build: .
    container_name: water-sensor-app-dev
    restart: always
    ports:
      - "5056:5055"
    networks:
      - water-sensor-network-dev
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  nginx:
    image: nginx:latest
    container_name: water-sensor-nginx-dev
    restart: always
    ports:
      - "8080:80"
      - "8086:8084"
      - "8087:8085"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - prometheus
      - grafana
    networks:
      - water-sensor-network-dev

  prometheus:
    image: prom/prometheus:latest
    container_name: water-sensor-prometheus-dev
    restart: always
    expose:
      - "9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_dev:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - water-sensor-network-dev

  grafana:
    image: grafana/grafana:latest
    container_name: water-sensor-grafana-dev
    restart: always
    expose:
      - "3000"
    volumes:
      - grafana_data_dev:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - water-sensor-network-dev

networks:
  water-sensor-network-dev:
    driver: bridge

volumes:
  prometheus_data_dev:
  grafana_data_dev:
