version: '3'

services:
  app:
    build: .
    container_name: water-sensor-app
    restart: always
    ports:
      - "5055:5055"
    networks:
      - water-sensor-network

  nginx:
    image: nginx:latest
    container_name: water-sensor-nginx
    restart: always
    ports:
      - "5066:80"
      - "8084:8084"
      - "8085:8085"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - prometheus
      - grafana
    networks:
      - water-sensor-network

  prometheus:
    image: prom/prometheus:latest
    container_name: water-sensor-prometheus
    restart: always
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - water-sensor-network

  grafana:
    image: grafana/grafana:latest
    container_name: water-sensor-grafana
    user: "472"
    restart: always
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_LOG_LEVEL=debug
    depends_on:
      - prometheus
    networks:
      - water-sensor-network

networks:
  water-sensor-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
