global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'water-sensor-dev'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:5055']
    metrics_path: '/metrics'
